// This file is generated by remix-fs-routes. Do not edit.
import { createController } from 'remix/router'
import { routes } from "./routes.ts"
import routeAction0 from "./routes/_index/action.tsx"
import routeAction1 from "./routes/($lang).hello/action.tsx"
import routeAction2 from "./routes/about/action.tsx"
import routeAction3 from "./routes/posts.$slug/action.tsx"

export const controller = createController(routes, {
  actions: {
    "_index": routeAction0,
    "($lang).hello": routeAction1,
    "about": routeAction2,
    "posts.$slug": routeAction3,
  },
})
