// This file is generated by remix-fs-routes. Do not edit.
import { createController } from 'remix/router'
import { routes } from "./routes.ts"
import { action as routeAction0 } from "./routes/_index/route.tsx"
import { action as routeAction1 } from "./routes/($lang).hello/route.tsx"
import { action as routeAction2 } from "./routes/about/route.tsx"
import { action as routeAction3 } from "./routes/posts.$slug/route.tsx"

export const controller = createController(routes, {
  actions: {
    "_index": routeAction0,
    "($lang).hello": routeAction1,
    "about": routeAction2,
    "posts.$slug": routeAction3,
  },
})
