// This file is generated by remix-fs-routes. Do not edit.
import { route as route0 } from "./routes/_index/+route.ts"
import { route as route1 } from "./routes/($lang).hello/+route.ts"
import { route as route2 } from "./routes/about/+route.ts"
import { route as route3 } from "./routes/posts.$slug/+route.ts"

export const routes = {
  "_index": route0,
  "($lang).hello": route1,
  "about": route2,
  "posts.$slug": route3,
}

export const routeManifest = [
    {
      "id": "_index",
      "file": "routes/_index/route.tsx",
      "pattern": "/",
      "index": true
    },
    {
      "id": "($lang).hello",
      "file": "routes/($lang).hello/route.tsx",
      "path": ":lang?/hello",
      "pattern": "(:lang/)hello",
      "index": false
    },
    {
      "id": "about",
      "file": "routes/about/route.tsx",
      "path": "about",
      "pattern": "/about",
      "index": false
    },
    {
      "id": "posts.$slug",
      "file": "routes/posts.$slug/route.tsx",
      "path": "posts/:slug",
      "pattern": "/posts/:slug",
      "index": false
    }
  ] as const
