// This file is generated by remix-fs-routes. Do not edit.
import { route } from 'remix/routes'

export const routes = route({
  "_index": "/",
  "($lang).hello": "(:lang/)hello",
  "about": "/about",
  "posts.$slug": "/posts/:slug",
})

export const routeManifest = [
    {
      "id": "_index",
      "file": "routes/_index/action.tsx",
      "pattern": "/",
      "index": true
    },
    {
      "id": "($lang).hello",
      "file": "routes/($lang).hello/action.tsx",
      "path": ":lang?/hello",
      "pattern": "(:lang/)hello",
      "index": false
    },
    {
      "id": "about",
      "file": "routes/about/action.tsx",
      "path": "about",
      "pattern": "/about",
      "index": false
    },
    {
      "id": "posts.$slug",
      "file": "routes/posts.$slug/action.tsx",
      "path": "posts/:slug",
      "pattern": "/posts/:slug",
      "index": false
    }
  ] as const
