// This file is generated by remix-fs-routes. Do not edit.
export function createRouteAction() {
  return (handlerOrOptions) => {
    if (typeof handlerOrOptions === 'function') return handlerOrOptions
    return (handler) => ({ ...handlerOrOptions, handler })
  }
}
