// This file is generated by remix-fs-routes. Do not edit.
import type {
  Action,
  Middleware,
  RequestContext,
  RequestHandler,
  RouterTypes,
} from 'remix/router'
import type { Route } from 'remix/routes'

type ActionRoute = string | Route
type AnyMiddleware = Middleware<any>
type DefaultContext = RouterTypes extends {
  context: infer context extends RequestContext<any, any>
}
  ? context
  : RequestContext
type ActionHandler<
  route extends ActionRoute,
  context extends RequestContext<any, any>,
> = Extract<Action<route, context>, RequestHandler<any>>
type ActionObject<
  route extends ActionRoute,
  context extends RequestContext<any, any>,
  middleware extends readonly AnyMiddleware[],
> = Extract<Action<route, context, middleware>, { handler: RequestHandler<any> }>

export interface RouteActionFactory<
  route extends ActionRoute,
  context extends RequestContext<any, any>,
> {
  (handler: ActionHandler<route, context>): ActionHandler<route, context>
  <const middleware extends readonly AnyMiddleware[]>(options: {
    middleware: readonly [...middleware]
  }): (
    handler: ActionObject<route, context, middleware>['handler'],
  ) => ActionObject<route, context, middleware>
}

export declare function createRouteAction<
  route extends ActionRoute,
  context extends RequestContext<any, any> = DefaultContext,
>(route: route): RouteActionFactory<route, context>
