packages:
  - 'test-app'

allowBuilds:
  core-js: true
  esbuild: true

minimumReleaseAgeExclude:
  - '@remix-run/assets@0.6.0'
  - '@remix-run/auth@0.3.0'
  - '@remix-run/cli@0.6.0'
  - '@remix-run/data-table-mysql@0.5.1'
  - '@remix-run/data-table-postgres@0.5.1'
  - '@remix-run/data-table-sqlite@0.6.1'
  - '@remix-run/data-table@0.5.0'
  - '@remix-run/render-middleware@0.2.0'
  - '@remix-run/spa@0.1.0'
  - '@remix-run/ui@0.8.0'
  - remix@3.0.0-rc.1

overrides:
  js-yaml: 4.1.0
  oxc-resolver: 11.23.0
  rolldown: 1.2.5
