// This file is generated by remix-fs-routes. Do not edit.
import { createHref, type CreateHrefArgs } from 'remix/route-pattern/href'
import { route } from 'remix/routes'

const routeDefs = {
  "_index": "/",
  "($lang).hello": "/(:lang/)hello",
  "about": "/about",
  "about._index": "/about/",
  "files.$": "/files/*",
  "frames.details": "/frames/details",
  "frames.summary": "/frames/summary",
  "posts.$slug": "/posts/:slug",
  "projects.$projectId.settings": "/projects/:projectId/settings",
  "reports.$reportId[.pdf]": "/reports/:reportId.pdf",
} as const

export const routes = route(routeDefs)

export type RoutePattern = typeof routeDefs[keyof typeof routeDefs]

export function href<const pattern extends RoutePattern>(
  pattern: pattern,
  ...args: CreateHrefArgs<pattern>
): string {
  return createHref(pattern, ...args)
}
