// This file is generated by remix-fs-routes. Do not edit.
import { createController, type RequestContext, type RouteBuilder, type RouterTypes } from 'remix/router'
import { routes } from "./routes.ts"
import routeAction0 from "./routes/_index/action.tsx"
import routeAction1 from "./routes/($lang).hello/action.tsx"
import routeAction2 from "./routes/about/action.tsx"
import routeAction3 from "./routes/about._index/action.tsx"
import routeAction4 from "./routes/files.$/action.tsx"
import routeAction5 from "./routes/frames.details/action.tsx"
import routeAction6 from "./routes/frames.summary/action.tsx"
import routeAction7 from "./routes/posts.$slug/action.tsx"
import routeAction8 from "./routes/projects.$projectId.settings/action.tsx"
import routeAction9 from "./routes/reports.$reportId[.pdf]/action.tsx"
import routeController0 from "./routes/frames/controller.ts"
import routeController1 from "./routes/frames.details/controller.ts"

const routeGroup0 = {
  "_index": routes["_index"],
  "($lang).hello": routes["($lang).hello"],
  "about": routes["about"],
  "about._index": routes["about._index"],
  "files.$": routes["files.$"],
  "posts.$slug": routes["posts.$slug"],
  "projects.$projectId.settings": routes["projects.$projectId.settings"],
  "reports.$reportId[.pdf]": routes["reports.$reportId[.pdf]"],
}

const routeGroup1 = {
  "frames.details": routes["frames.details"],
}

const routeGroup2 = {
  "frames.summary": routes["frames.summary"],
}

type DefaultContext = RouterTypes extends {
  context: infer context extends RequestContext<any, any>
}
  ? context
  : RequestContext

export function registerRoutes(router: RouteBuilder<DefaultContext>): void {
  router.map(routeGroup0, createController(routeGroup0, {
    actions: {
      "_index": routeAction0,
      "($lang).hello": routeAction1,
      "about": routeAction2,
      "about._index": routeAction3,
      "files.$": routeAction4,
      "posts.$slug": routeAction7,
      "projects.$projectId.settings": routeAction8,
      "reports.$reportId[.pdf]": routeAction9,
    },
  }))
  router.map(routeGroup1, createController(routeGroup1, {
    middleware: [
      ...routeController0.middleware,
      ...routeController1.middleware,
    ],
    actions: {
      "frames.details": routeAction5,
    },
  }))
  router.map(routeGroup2, createController(routeGroup2, {
    middleware: [
      ...routeController0.middleware,
    ],
    actions: {
      "frames.summary": routeAction6,
    },
  }))
}
