// This file is generated by remix-fs-routes. Do not edit.
import { type RequestContext, type RouteBuilder, type RouterTypes } from 'remix/router'
import { registerRouteModule } from "./routes.support.js"
import { routes } from "./routes.ts"
import * as routeModule0 from "./routes/_index/actions.tsx"
import * as routeModule1 from "./routes/($lang).hello/actions.tsx"
import * as routeModule2 from "./routes/about/actions.tsx"
import * as routeModule3 from "./routes/about._index/actions.tsx"
import * as routeModule4 from "./routes/files.$/actions.tsx"
import * as routeModule5 from "./routes/frames.details/actions.tsx"
import * as routeModule6 from "./routes/frames.summary/actions.tsx"
import * as routeModule7 from "./routes/posts.$slug/actions.tsx"
import * as routeModule8 from "./routes/projects.$projectId.settings/actions.tsx"
import * as routeModule9 from "./routes/reports.$reportId[.pdf]/actions.tsx"
import routeController0 from "./routes/frames/controller.ts"
import routeController1 from "./routes/frames.details/controller.ts"

type DefaultContext = RouterTypes extends {
  context: infer context extends RequestContext<any, any>
}
  ? context
  : RequestContext

export function registerRoutes(router: RouteBuilder<DefaultContext>): void {
  registerRouteModule(router, routes["_index"], routeModule0)
  registerRouteModule(router, routes["($lang).hello"], routeModule1)
  registerRouteModule(router, routes["about"], routeModule2)
  registerRouteModule(router, routes["about._index"], routeModule3)
  registerRouteModule(router, routes["files.$"], routeModule4)
  registerRouteModule(router, routes["frames.details"], routeModule5, [
    ...routeController0.middleware,
    ...routeController1.middleware,
  ])
  registerRouteModule(router, routes["frames.summary"], routeModule6, [
    ...routeController0.middleware,
  ])
  registerRouteModule(router, routes["posts.$slug"], routeModule7)
  registerRouteModule(router, routes["projects.$projectId.settings"], routeModule8)
  registerRouteModule(router, routes["reports.$reportId[.pdf]"], routeModule9)
}
