import path from 'node:path'

import { resolveOptions, scanRoutes } from './convention.js'
import type {
  GenerateRouteArtifactsOptions,
  GenerateRouteArtifactsResult,
  GeneratedRouteArtifact,
  RouteManifest,
} from './types.js'

export const generatedFileHeader = '// This file is generated by remix-fs-routes. Do not edit.'

const identifierPattern = /^[A-Za-z_$][\w$]*$/

export async function generateRouteArtifacts(
  options: GenerateRouteArtifactsOptions = {},
): Promise<GenerateRouteArtifactsResult> {
  let resolved = resolveOptions(options)
  let routesOutput = path.resolve(resolved.cwd, options.routesOutput ?? 'app/routes.ts')
  let controllerOutput = path.resolve(
    resolved.cwd,
    options.controllerOutput ?? 'app/routes.controller.ts',
  )
  let typegenDirectory = path.resolve(
    resolved.cwd,
    options.typegenDirectory ?? '.remix-fs-routes/types',
  )
  let routesExportName = options.routesExportName ?? 'routes'
  let controllerExportName = options.controllerExportName ?? 'controller'
  validateIdentifier(routesExportName, 'routes export')
  validateIdentifier(controllerExportName, 'controller export')
  validateOutputExtension(routesOutput)
  validateOutputExtension(controllerOutput)

  let manifest = await scanRoutes(options)
  let artifacts: GeneratedRouteArtifact[] = []

  for (let entry of manifest.routes) {
    let routeModule = path.resolve(resolved.appDirectory, entry.file)
    artifacts.push({
      kind: 'route-module',
      output: path.join(path.dirname(routeModule), '+route.ts'),
      routeId: entry.id,
      source: generateRouteModuleSource(entry.pattern),
    })
  }

  artifacts.push(
    {
      kind: 'routes',
      output: routesOutput,
      source: generateRoutesSource(
        manifest,
        resolved.appDirectory,
        routesOutput,
        routesExportName,
        isTypeScriptOutput(routesOutput),
      ),
    },
    {
      kind: 'controller',
      output: controllerOutput,
      source: generateControllerSource(
        manifest,
        resolved.appDirectory,
        controllerOutput,
        routesOutput,
        routesExportName,
        controllerExportName,
      ),
    },
    {
      kind: 'virtual-types',
      output: path.join(typegenDirectory, 'virtual.d.ts'),
      source: generateVirtualTypesSource(
        manifest,
        routesVirtualModuleId(options),
        controllerVirtualModuleId(options),
        routesExportName,
        controllerExportName,
      ),
    },
  )

  return { artifacts, manifest }
}

function generateRoutesSource(
  manifest: RouteManifest,
  appDirectory: string,
  output: string,
  exportName: string,
  typescript: boolean,
): string {
  let imports = manifest.routes.map((entry, index) => {
    let routeModule = path.resolve(appDirectory, entry.file)
    let companion = path.join(path.dirname(routeModule), '+route.ts')
    return `import { route as route${index} } from ${JSON.stringify(relativeImport(output, companion))}`
  })
  let definitions = manifest.routes
    .map((entry, index) => `  ${JSON.stringify(entry.id)}: route${index},`)
    .join('\n')
  let serializedManifest = indent(JSON.stringify(manifest.routes, null, 2))
  return [
    generatedFileHeader,
    ...imports,
    '',
    `export const ${exportName} = {`,
    definitions,
    '}',
    '',
    `export const routeManifest = ${serializedManifest}${typescript ? ' as const' : ''}`,
    '',
  ].join('\n')
}

function generateControllerSource(
  manifest: RouteManifest,
  appDirectory: string,
  output: string,
  routesOutput: string,
  routesExportName: string,
  controllerExportName: string,
): string {
  let imports = manifest.routes.map((entry, index) => {
    let routeModule = path.resolve(appDirectory, entry.file)
    return `import { action as routeAction${index} } from ${JSON.stringify(relativeImport(output, routeModule))}`
  })
  let actions = manifest.routes
    .map((entry, index) => `    ${JSON.stringify(entry.id)}: routeAction${index},`)
    .join('\n')
  return [
    generatedFileHeader,
    "import { createController } from 'remix/router'",
    `import { ${routesExportName} } from ${JSON.stringify(relativeImport(output, routesOutput))}`,
    ...imports,
    '',
    `export const ${controllerExportName} = createController(${routesExportName}, {`,
    '  actions: {',
    actions,
    '  },',
    '})',
    '',
  ].join('\n')
}

function generateRouteModuleSource(pattern: string): string {
  return [
    generatedFileHeader,
    "import { createRouteModule } from 'remix-fs-routes/route-module'",
    '',
    `export const { route, createAction } = createRouteModule(${JSON.stringify(pattern)})`,
    '',
  ].join('\n')
}

function generateVirtualTypesSource(
  manifest: RouteManifest,
  routesModuleId: string,
  controllerModuleId: string,
  routesExportName: string,
  controllerExportName: string,
): string {
  let routeTypes = manifest.routes
    .map((entry) => `    readonly ${JSON.stringify(entry.id)}: Route<'ANY', ${JSON.stringify(absolutePattern(entry.pattern))}>`)
    .join('\n')
  return [
    generatedFileHeader,
    `declare module ${JSON.stringify(routesModuleId)} {`,
    "  import type { Route } from 'remix/routes'",
    '',
    `  export const ${routesExportName}: {`,
    routeTypes,
    '  }',
    `  export const routeManifest: readonly {`,
    '    readonly id: string',
    '    readonly file: string',
    '    readonly path?: string',
    '    readonly pattern: string',
    '    readonly parentId?: string',
    '    readonly index: boolean',
    '  }[]',
    '}',
    '',
    `declare module ${JSON.stringify(controllerModuleId)} {`,
    "  import type { Controller } from 'remix/router'",
    `  import type { ${routesExportName} } from ${JSON.stringify(routesModuleId)}`,
    '',
    `  export const ${controllerExportName}: Controller<typeof ${routesExportName}>`,
    '}',
    '',
  ].join('\n')
}

function absolutePattern(pattern: string): string {
  return pattern.startsWith('/') ? pattern : `/${pattern}`
}

function routesVirtualModuleId(options: GenerateRouteArtifactsOptions): string {
  return 'routesVirtualModuleId' in options && typeof options.routesVirtualModuleId === 'string'
    ? options.routesVirtualModuleId
    : 'virtual:remix-fs-routes/routes'
}

function controllerVirtualModuleId(options: GenerateRouteArtifactsOptions): string {
  return 'controllerVirtualModuleId' in options &&
    typeof options.controllerVirtualModuleId === 'string'
    ? options.controllerVirtualModuleId
    : 'virtual:remix-fs-routes/controller'
}

function validateIdentifier(value: string, label: string): void {
  if (!identifierPattern.test(value)) throw new TypeError(`Invalid ${label} name "${value}".`)
}

function validateOutputExtension(output: string): void {
  if (!['.ts', '.mts', '.js', '.mjs'].includes(path.extname(output))) {
    throw new TypeError(`Generated output ${output} must use .ts, .mts, .js, or .mjs.`)
  }
}

function isTypeScriptOutput(output: string): boolean {
  return ['.ts', '.mts'].includes(path.extname(output))
}

function relativeImport(fromFile: string, toFile: string): string {
  let relative = path.relative(path.dirname(fromFile), toFile).split(path.sep).join('/')
  return relative.startsWith('.') ? relative : `./${relative}`
}

function indent(value: string): string {
  return value
    .split('\n')
    .map((line, index) => (index === 0 ? line : `  ${line}`))
    .join('\n')
}
