import path from 'node:path'

import { resolveOptions, scanRoutes } from './convention.js'
import type {
  GenerateRouteArtifactsOptions,
  GenerateRouteArtifactsResult,
  GeneratedRouteArtifact,
  RouteManifest,
  RouteManifestEntry,
} from './types.js'

export const generatedFileHeader = '// This file is generated by remix-fs-routes. Do not edit.'

const identifierPattern = /^[A-Za-z_$][\w$]*$/
const routesVirtualModuleId = 'virtual:remix-fs-routes/routes'
const controllerVirtualModuleId = 'virtual:remix-fs-routes/controller'

export async function generateRouteArtifacts(
  options: GenerateRouteArtifactsOptions = {},
): Promise<GenerateRouteArtifactsResult> {
  let resolved = resolveOptions(options)
  let routesOutput = path.resolve(resolved.cwd, options.routesOutput ?? 'app/routes.ts')
  let controllerOutput = path.resolve(
    resolved.cwd,
    options.controllerOutput ?? 'app/routes.controller.ts',
  )
  let typegenDirectory = path.resolve(
    resolved.cwd,
    options.typegenDirectory ?? '.remix-fs-routes/types',
  )
  let routesExportName = options.routesExportName ?? 'routes'
  let controllerExportName = options.controllerExportName ?? 'registerRoutes'
  let supportOutput = getRouteSupportOutput(routesOutput)
  let supportTypesOutput = getRouteSupportTypesOutput(routesOutput)
  validateIdentifier(routesExportName, 'routes export')
  validateIdentifier(controllerExportName, 'controller export')
  validateOutputExtension(routesOutput)
  validateOutputExtension(controllerOutput)

  let manifest = await scanRoutes(options)
  let artifacts: GeneratedRouteArtifact[] = []

  for (let entry of manifest.routes) {
    let routeModule = path.resolve(resolved.appDirectory, entry.file)
    artifacts.push({
      kind: 'route-module',
      output: path.join(path.dirname(routeModule), '+route.ts'),
      routeId: entry.id,
      source: generateRouteModuleSource(
        entry,
        manifest,
        resolved.appDirectory,
        path.join(path.dirname(routeModule), '+route.ts'),
        routesOutput,
        supportOutput,
        routesExportName,
      ),
    })
  }

  for (let entry of manifest.controllers) {
    let controllerModule = path.resolve(resolved.appDirectory, entry.file)
    artifacts.push({
      kind: 'controller-module',
      output: path.join(path.dirname(controllerModule), '+controller.ts'),
      controllerId: entry.id,
      source: generateControllerModuleSource(
        path.join(path.dirname(controllerModule), '+controller.ts'),
        supportOutput,
      ),
    })
  }

  artifacts.push(
    {
      kind: 'route-support',
      output: supportOutput,
      source: generateRouteSupportSource(),
    },
    {
      kind: 'route-support',
      output: supportTypesOutput,
      source: generateRouteSupportTypesSource(),
    },
    {
      kind: 'routes',
      output: routesOutput,
      source: generateRoutesSource(
        manifest,
        routesOutput,
        routesExportName,
        isTypeScriptOutput(routesOutput),
      ),
    },
    {
      kind: 'controller',
      output: controllerOutput,
      source: generateControllerSource(
        manifest,
        resolved.appDirectory,
        controllerOutput,
        routesOutput,
        routesExportName,
        controllerExportName,
      ),
    },
    {
      kind: 'virtual-types',
      output: path.join(typegenDirectory, 'virtual.d.ts'),
      source: generateVirtualTypesSource(
        manifest,
        routesVirtualModuleId,
        controllerVirtualModuleId,
        routesExportName,
        controllerExportName,
      ),
    },
  )

  return { artifacts, manifest }
}

function generateRoutesSource(
  manifest: RouteManifest,
  output: string,
  exportName: string,
  typescript: boolean,
): string {
  let routeDefsName = exportName === 'routeDefs' ? 'generatedRouteDefs' : 'routeDefs'
  let definitions = manifest.routes
    .map(
      (entry) =>
        `  ${JSON.stringify(entry.id)}: ${JSON.stringify(absolutePattern(entry.pattern))},`,
    )
    .join('\n')
  let hrefSource = typescript
    ? [
        `export type RoutePattern = typeof ${routeDefsName}[keyof typeof ${routeDefsName}]`,
        '',
        'export function href<const pattern extends RoutePattern>(',
        '  pattern: pattern,',
        '  ...args: CreateHrefArgs<pattern>',
        '): string {',
        '  return createHref(pattern, ...args)',
        '}',
      ]
    : ['export function href(pattern, ...args) {', '  return createHref(pattern, ...args)', '}']
  return [
    generatedFileHeader,
    typescript
      ? "import { createHref, type CreateHrefArgs } from 'remix/route-pattern/href'"
      : "import { createHref } from 'remix/route-pattern/href'",
    "import { route } from 'remix/routes'",
    '',
    `const ${routeDefsName} = {`,
    definitions,
    `}${typescript ? ' as const' : ''}`,
    '',
    `export const ${exportName} = route(${routeDefsName})`,
    '',
    ...hrefSource,
    '',
  ].join('\n')
}

function generateControllerSource(
  manifest: RouteManifest,
  appDirectory: string,
  output: string,
  routesOutput: string,
  routesExportName: string,
  controllerExportName: string,
): string {
  let actionImports = manifest.routes.map((entry, index) => {
    let routeModule = path.resolve(appDirectory, entry.file)
    return `import * as routeModule${index} from ${JSON.stringify(relativeImport(output, routeModule))}`
  })
  let controllerImports = manifest.controllers.map((entry, index) => {
    let controllerModule = path.resolve(appDirectory, entry.file)
    return `import routeController${index} from ${JSON.stringify(relativeImport(output, controllerModule))}`
  })
  let registrations = manifest.routes.flatMap((entry, routeIndex) => {
    let middleware = entry.controllerIds.map((id) => {
      let controllerIndex = manifest.controllers.findIndex((entry) => entry.id === id)
      return `    ...routeController${controllerIndex}.middleware,`
    })
    let call = `  registerRouteModule(router, ${routesExportName}[${JSON.stringify(entry.id)}], routeModule${routeIndex}`
    return middleware.length > 0 ? [call + ', [', ...middleware, '  ])'] : [call + ')']
  })
  let typescript = isTypeScriptOutput(output)
  return [
    generatedFileHeader,
    typescript
      ? "import { type RequestContext, type RouteBuilder, type RouterTypes } from 'remix/router'"
      : '',
    `import { registerRouteModule } from ${JSON.stringify(relativeImport(output, getRouteSupportOutput(routesOutput)))}`,
    `import { ${routesExportName} } from ${JSON.stringify(relativeImport(output, routesOutput))}`,
    ...actionImports,
    ...controllerImports,
    '',
    ...(typescript
      ? [
          'type DefaultContext = RouterTypes extends {',
          '  context: infer context extends RequestContext<any, any>',
          '}',
          '  ? context',
          '  : RequestContext',
          '',
        ]
      : []),
    typescript
      ? `export function ${controllerExportName}(router: RouteBuilder<DefaultContext>): void {`
      : `export function ${controllerExportName}(router) {`,
    ...registrations,
    '}',
    '',
  ].join('\n')
}

function generateRouteModuleSource(
  entry: RouteManifestEntry,
  manifest: RouteManifest,
  appDirectory: string,
  output: string,
  routesOutput: string,
  supportOutput: string,
  routesExportName: string,
): string {
  let controllerImports = entry.controllerIds.map((controllerId, index) => {
    let controller = manifest.controllers.find((entry) => entry.id === controllerId)!
    let controllerModule = path.resolve(appDirectory, controller.file)
    return `import type routeController${index} from ${JSON.stringify(relativeImport(output, controllerModule))}`
  })
  let middlewareType = entry.controllerIds.map(
    (_, index) => `  ...ControllerMiddleware<typeof routeController${index}>,`,
  )
  return [
    generatedFileHeader,
    `import { ${routesExportName} } from ${JSON.stringify(relativeImport(output, routesOutput))}`,
    `import { createRouteAction } from ${JSON.stringify(relativeImport(output, supportOutput))}`,
    ...(controllerImports.length > 0
      ? [
          `import type { ControllerContext, ControllerMiddleware } from ${JSON.stringify(relativeImport(output, supportOutput))}`,
          ...controllerImports,
        ]
      : []),
    '',
    `export const route = ${routesExportName}[${JSON.stringify(entry.id)}]`,
    ...(middlewareType.length > 0
      ? [
          'type InheritedMiddleware = [',
          ...middlewareType,
          ']',
          '',
          'export const createAction = createRouteAction<',
          '  typeof route,',
          '  ControllerContext<InheritedMiddleware>',
          '>(route)',
        ]
      : ['export const createAction = createRouteAction(route)']),
    '',
  ].join('\n')
}

function generateControllerModuleSource(output: string, supportOutput: string): string {
  return [
    generatedFileHeader,
    `import { createRouteController } from ${JSON.stringify(relativeImport(output, supportOutput))}`,
    '',
    'export const createController = createRouteController()',
    '',
  ].join('\n')
}

function generateRouteSupportSource(): string {
  return [
    generatedFileHeader,
    'const routeMethods = {',
    "  get: 'GET',",
    "  head: 'HEAD',",
    "  post: 'POST',",
    "  put: 'PUT',",
    "  patch: 'PATCH',",
    "  delete: 'DELETE',",
    "  options: 'OPTIONS',",
    '}',
    '',
    'const unsupportedRouteMethods = {',
    "  connect: 'CONNECT',",
    "  trace: 'TRACE',",
    '}',
    '',
    'export function createRouteAction() {',
    '  return (handlerOrOptions) => {',
    "    if (typeof handlerOrOptions === 'function') return handlerOrOptions",
    '    return (handler) => ({ ...handlerOrOptions, handler })',
    '  }',
    '}',
    '',
    'export function createRouteController() {',
    '  return (options) => options',
    '}',
    '',
    'export function registerRouteModule(router, route, routeModule, middleware = []) {',
    '  for (let name in unsupportedRouteMethods) {',
    '    if (Object.hasOwn(routeModule, name)) {',
    '      throw new TypeError(',
    '        `Route module export "${name}" cannot be registered: the Fetch Request API and Remix router do not support ${unsupportedRouteMethods[name]} requests.`,',
    '      )',
    '    }',
    '  }',
    '',
    '  for (let name in routeMethods) {',
    '    if (Object.hasOwn(routeModule, name)) {',
    '      router.route(routeMethods[name], route, mergeActionMiddleware(routeModule[name], middleware))',
    '    }',
    '  }',
    '',
    "  if (Object.hasOwn(routeModule, 'default')) {",
    '    router.map(route, mergeActionMiddleware(routeModule.default, middleware))',
    '  }',
    '}',
    '',
    'function mergeActionMiddleware(action, middleware) {',
    '  if (middleware.length === 0) return action',
    "  if (typeof action === 'function') return { handler: action, middleware }",
    '  return {',
    '    ...action,',
    '    middleware: [...middleware, ...(action.middleware ?? [])],',
    '  }',
    '}',
    '',
  ].join('\n')
}

function generateRouteSupportTypesSource(): string {
  return [
    generatedFileHeader,
    'import type {',
    '  Action,',
    '  Middleware,',
    '  MiddlewareContext,',
    '  RequestContext,',
    '  RequestHandler,',
    '  RouteBuilder,',
    '  RouterTypes,',
    "} from 'remix/router'",
    "import type { Route } from 'remix/routes'",
    '',
    'type ActionRoute = string | Route',
    'export type AnyMiddleware = Middleware<any>',
    'type DefaultContext = RouterTypes extends {',
    '  context: infer context extends RequestContext<any, any>',
    '}',
    '  ? context',
    '  : RequestContext',
    'export type ControllerMiddleware<controller> = controller extends {',
    '  middleware: infer middleware extends readonly AnyMiddleware[]',
    '}',
    '  ? middleware',
    '  : []',
    'export type ControllerContext<middleware extends readonly AnyMiddleware[]> =',
    '  MiddlewareContext<middleware, DefaultContext>',
    'type ActionHandler<',
    '  route extends ActionRoute,',
    '  context extends RequestContext<any, any>,',
    '> = Extract<Action<route, context>, RequestHandler<any>>',
    'type ActionObject<',
    '  route extends ActionRoute,',
    '  context extends RequestContext<any, any>,',
    '  middleware extends readonly AnyMiddleware[],',
    '> = Extract<Action<route, context, middleware>, { handler: RequestHandler<any> }>',
    '',
    'export interface RouteActionFactory<',
    '  route extends ActionRoute,',
    '  context extends RequestContext<any, any>,',
    '> {',
    '  (handler: ActionHandler<route, context>): ActionHandler<route, context>',
    '  <const middleware extends readonly AnyMiddleware[]>(options: {',
    '    middleware: readonly [...middleware]',
    '  }): (',
    "    handler: ActionObject<route, context, middleware>['handler'],",
    '  ) => ActionObject<route, context, middleware>',
    '}',
    '',
    'export declare function createRouteAction<',
    '  route extends ActionRoute,',
    '  context extends RequestContext<any, any> = DefaultContext,',
    '>(route: route): RouteActionFactory<route, context>',
    '',
    'export interface RouteControllerFactory {',
    '  <const middleware extends readonly AnyMiddleware[]>(options: {',
    '    middleware: readonly [...middleware]',
    '  }): { middleware: readonly [...middleware] }',
    '}',
    '',
    'export declare function createRouteController(): RouteControllerFactory',
    '',
    "export type RouteMethodExport = 'get' | 'head' | 'post' | 'put' | 'patch' | 'delete' | 'options'",
    "export type UnsupportedRouteMethodExport = 'connect' | 'trace'",
    'export type StandardRouteMethodExport = RouteMethodExport | UnsupportedRouteMethodExport',
    'export type RouteActionModule = {',
    '  default?: unknown',
    '} & Partial<Record<StandardRouteMethodExport, unknown>>',
    '',
    'export declare function registerRouteModule<',
    '  context extends RequestContext<any, any>,',
    '  route extends ActionRoute,',
    '  const middleware extends readonly AnyMiddleware[] = [],',
    '>(',
    '  router: RouteBuilder<context>,',
    '  route: route,',
    '  routeModule: RouteActionModule,',
    '  middleware?: readonly [...middleware],',
    '): void',
    '',
  ].join('\n')
}

function generateVirtualTypesSource(
  manifest: RouteManifest,
  routesModuleId: string,
  controllerModuleId: string,
  routesExportName: string,
  controllerExportName: string,
): string {
  let routePatterns = [...new Set(manifest.routes.map((entry) => absolutePattern(entry.pattern)))]
  let routePatternType =
    routePatterns.length > 0
      ? routePatterns.map((pattern) => JSON.stringify(pattern)).join(' | ')
      : 'never'
  let routeTypes = manifest.routes
    .map(
      (entry) =>
        `    readonly ${JSON.stringify(entry.id)}: Route<'ANY', ${JSON.stringify(absolutePattern(entry.pattern))}>`,
    )
    .join('\n')
  return [
    generatedFileHeader,
    `declare module ${JSON.stringify(routesModuleId)} {`,
    "  import type { CreateHrefArgs } from 'remix/route-pattern/href'",
    "  import type { Route } from 'remix/routes'",
    '',
    `  export type RoutePattern = ${routePatternType}`,
    '  export function href<const pattern extends RoutePattern>(',
    '    pattern: pattern,',
    '    ...args: CreateHrefArgs<pattern>',
    '  ): string',
    '',
    `  export const ${routesExportName}: {`,
    routeTypes,
    '  }',
    '}',
    '',
    `declare module ${JSON.stringify(controllerModuleId)} {`,
    "  import type { RequestContext, RouteBuilder, RouterTypes } from 'remix/router'",
    '',
    '  type DefaultContext = RouterTypes extends {',
    '    context: infer context extends RequestContext<any, any>',
    '  }',
    '    ? context',
    '    : RequestContext',
    '',
    `  export function ${controllerExportName}(`,
    '    router: RouteBuilder<DefaultContext>,',
    '  ): void',
    '}',
    '',
  ].join('\n')
}

function absolutePattern(pattern: string): string {
  return pattern.startsWith('/') ? pattern : `/${pattern}`
}

function validateIdentifier(value: string, label: string): void {
  if (!identifierPattern.test(value)) throw new TypeError(`Invalid ${label} name "${value}".`)
}

function validateOutputExtension(output: string): void {
  if (!['.ts', '.mts', '.js', '.mjs'].includes(path.extname(output))) {
    throw new TypeError(`Generated output ${output} must use .ts, .mts, .js, or .mjs.`)
  }
}

function isTypeScriptOutput(output: string): boolean {
  return ['.ts', '.mts'].includes(path.extname(output))
}

export function getRouteSupportOutput(routesOutput: string): string {
  let extension = path.extname(routesOutput)
  return `${routesOutput.slice(0, -extension.length)}.support.js`
}

export function getRouteSupportTypesOutput(routesOutput: string): string {
  let extension = path.extname(routesOutput)
  return `${routesOutput.slice(0, -extension.length)}.support.d.ts`
}

function relativeImport(fromFile: string, toFile: string): string {
  let relative = path.relative(path.dirname(fromFile), toFile).split(path.sep).join('/')
  return relative.startsWith('.') ? relative : `./${relative}`
}
