import path from 'node:path'

import { resolveOptions, scanRoutes } from './convention.js'
import type {
  GenerateRouteArtifactsOptions,
  GenerateRouteArtifactsResult,
  GeneratedRouteArtifact,
  RouteManifest,
} from './types.js'

export const generatedFileHeader = '// This file is generated by remix-fs-routes. Do not edit.'

const identifierPattern = /^[A-Za-z_$][\w$]*$/

export async function generateRouteArtifacts(
  options: GenerateRouteArtifactsOptions = {},
): Promise<GenerateRouteArtifactsResult> {
  let resolved = resolveOptions(options)
  let routesOutput = path.resolve(resolved.cwd, options.routesOutput ?? 'app/routes.ts')
  let controllerOutput = path.resolve(
    resolved.cwd,
    options.controllerOutput ?? 'app/routes.controller.ts',
  )
  let routesExportName = options.routesExportName ?? 'routes'
  let controllerExportName = options.controllerExportName ?? 'controller'
  validateIdentifier(routesExportName, 'routes export')
  validateIdentifier(controllerExportName, 'controller export')
  validateOutputExtension(routesOutput)
  validateOutputExtension(controllerOutput)

  let manifest = await scanRoutes(options)
  let artifacts: GeneratedRouteArtifact[] = [
    {
      kind: 'routes',
      output: routesOutput,
      source: generateRoutesSource(manifest, routesExportName, isTypeScriptOutput(routesOutput)),
    },
    {
      kind: 'controller',
      output: controllerOutput,
      source: generateControllerSource(
        manifest,
        resolved.appDirectory,
        controllerOutput,
        routesOutput,
        routesExportName,
        controllerExportName,
      ),
    },
  ]

  for (let entry of manifest.routes) {
    let routeModule = path.resolve(resolved.appDirectory, entry.file)
    let output = path.join(path.dirname(routeModule), '+route.ts')
    artifacts.push({
      kind: 'companion',
      output,
      routeId: entry.id,
      source: generateCompanionSource(output, routesOutput, routesExportName, entry.id),
    })
  }

  return { artifacts, manifest }
}

function generateRoutesSource(
  manifest: RouteManifest,
  exportName: string,
  typescript: boolean,
): string {
  let definitions = manifest.routes
    .map((entry) => `  ${JSON.stringify(entry.id)}: ${JSON.stringify(entry.pattern)},`)
    .join('\n')
  let serializedManifest = indent(JSON.stringify(manifest.routes, null, 2))
  return [
    generatedFileHeader,
    "import { route } from 'remix/routes'",
    '',
    `export const ${exportName} = route({`,
    definitions,
    '})',
    '',
    `export const routeManifest = ${serializedManifest}${typescript ? ' as const' : ''}`,
    '',
  ].join('\n')
}

function generateControllerSource(
  manifest: RouteManifest,
  appDirectory: string,
  output: string,
  routesOutput: string,
  routesExportName: string,
  controllerExportName: string,
): string {
  let imports = manifest.routes.map((entry, index) => {
    let routeModule = path.resolve(appDirectory, entry.file)
    return `import { action as routeAction${index} } from ${JSON.stringify(relativeImport(output, routeModule))}`
  })
  let actions = manifest.routes
    .map((entry, index) => `    ${JSON.stringify(entry.id)}: routeAction${index},`)
    .join('\n')
  return [
    generatedFileHeader,
    "import { createController } from 'remix/router'",
    `import { ${routesExportName} } from ${JSON.stringify(relativeImport(output, routesOutput))}`,
    ...imports,
    '',
    `export const ${controllerExportName} = createController(${routesExportName}, {`,
    '  actions: {',
    actions,
    '  },',
    '})',
    '',
  ].join('\n')
}

function generateCompanionSource(
  output: string,
  routesOutput: string,
  routesExportName: string,
  routeId: string,
): string {
  return [
    generatedFileHeader,
    `import { ${routesExportName} } from ${JSON.stringify(relativeImport(output, routesOutput))}`,
    '',
    `export const route = ${routesExportName}[${JSON.stringify(routeId)}]`,
    '',
  ].join('\n')
}

function validateIdentifier(value: string, label: string): void {
  if (!identifierPattern.test(value)) throw new TypeError(`Invalid ${label} name "${value}".`)
}

function validateOutputExtension(output: string): void {
  if (!['.ts', '.mts', '.js', '.mjs'].includes(path.extname(output))) {
    throw new TypeError(`Generated output ${output} must use .ts, .mts, .js, or .mjs.`)
  }
}

function isTypeScriptOutput(output: string): boolean {
  return ['.ts', '.mts'].includes(path.extname(output))
}

function relativeImport(fromFile: string, toFile: string): string {
  let relative = path.relative(path.dirname(fromFile), toFile).split(path.sep).join('/')
  return relative.startsWith('.') ? relative : `./${relative}`
}

function indent(value: string): string {
  return value
    .split('\n')
    .map((line, index) => (index === 0 ? line : `  ${line}`))
    .join('\n')
}
