on:
  pull_request:
    branches:
      - main

jobs:
  pr-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - uses: pnpm/setup@703c52620218391530e48b9e8870d5c0082e1b9b
      - run: pnpm check && pnpm build
